name: Generate prebuilt images bnbnbnb
on: [push, pull_request]

jobs:
  buildroot:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        defconfig_name: [qemu_x86_defconfig, qemu_x86_64_defconfig, raspberrypi4_defconfig, raspberrypi4_64_defconfig, qemu_ppc64le_pseries_defconfig, qemu_mips32r2_malta_defconfig, qemu_mips64_malta_defconfig]
        libc_name: [glibc, uclibc, musl]
    env:
      BUILDROOT_DIRECTORY_NAME: /home/runner/buildroot-${{ matrix.defconfig_name }}-${{ matrix.libc_name }}
    permissions:
      contents: write
    steps:
      - name: Retrieve CI scripts
        uses: actions/checkout@v3
      - name: bof
        run: |
            echo bonjour > ${{ env.BUILDROOT_DIRECTORY_NAME }}.tar.zst
      - name: Deploy image to repository release
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BUILDROOT_DIRECTORY_NAME }}.tar.zst
          tag: ${{ github.ref_name }}
          overwrite: true
          prerelease: true
          release_name: Continuous deployment
